/*
 * SUNSHINE TEAHOUSE PRIVATE LIMITED CONFIDENTIAL
 * __________________
 *
 * [2015] - [2017] Sunshine Teahouse Private Limited
 * All Rights Reserved.
 *
 * NOTICE:  All information contained herein is, and remains
 * the property of Sunshine Teahouse Private Limited and its suppliers,
 * if any.  The intellectual and technical concepts contained
 * herein are proprietary to Sunshine Teahouse Private Limited
 * and its suppliers, and are protected by trade secret or copyright law.
 * Dissemination of this information or reproduction of this material
 * is strictly forbidden unless prior written permission is obtained
 * from Sunshine Teahouse Private Limited.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.23 at 04:31:07 PM IST 
//


package www.chaayos.com.chaimonkbluetoothapp.domain.model.new_model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

public class AddonList  implements Serializable{

	private static final long serialVersionUID = -4522153727684531648L;

    protected IdCodeName detail;

    protected List<AddonData> content;


    public IdCodeName getDetail() {
        return detail;
    }


    public void setDetail(IdCodeName value) {
        this.detail = value;
    }


    public List<AddonData> getContent() {
        if (content == null) {
            content = new ArrayList<AddonData>();
        }
        return this.content;
    }

}
