/*
 * SUNSHINE TEAHOUSE PRIVATE LIMITED CONFIDENTIAL
 * __________________
 *
 * [2015] - [2017] Sunshine Teahouse Private Limited
 * All Rights Reserved.
 *
 * NOTICE:  All information contained herein is, and remains
 * the property of Sunshine Teahouse Private Limited and its suppliers,
 * if any.  The intellectual and technical concepts contained
 * herein are proprietary to Sunshine Teahouse Private Limited
 * and its suppliers, and are protected by trade secret or copyright law.
 * Dissemination of this information or reproduction of this material
 * is strictly forbidden unless prior written permission is obtained
 * from Sunshine Teahouse Private Limited.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.24 at 05:01:33 PM IST 
//

package www.chaayos.com.chaimonkbluetoothapp.domain.model.new_model;

import java.io.Serializable;


public class Address implements Serializable {

	private String objectId;

	private Long version;

	/**
	 * Added to avoid a runtime error whereby the detachAll property is checked
	 * for existence but not actually used.
	 */
	private String detachAll;

	/**
	 * 
	 */
	private static final long serialVersionUID = 8075917195527246495L;
	protected int id;
	protected String line1;
	protected String line2;
	protected String line3;
	protected String locality;
	protected String city;
	protected String state;
	protected String country;
	protected String zipCode;
	protected String contact1;
	protected String contact2;
	protected String addressType;
	protected String company;
	protected String latitude;
	protected String longitude;
	protected Boolean preferredAddress;

	/**
	 * Gets the value of the id property.
	 * 
	 */
	public int getId() {
		return id;
	}

	/**
	 * Sets the value of the id property.
	 * 
	 */
	public void setId(int value) {
		this.id = value;
	}

	/**
	 * Gets the value of the line1 property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getLine1() {
		return line1;
	}

	/**
	 * Sets the value of the line1 property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setLine1(String value) {
		this.line1 = value;
	}

	/**
	 * Gets the value of the line2 property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getLine2() {
		return line2;
	}

	/**
	 * Sets the value of the line2 property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setLine2(String value) {
		this.line2 = value;
	}

	/**
	 * Gets the value of the line3 property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getLine3() {
		return line3;
	}

	/**
	 * Sets the value of the line3 property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setLine3(String value) {
		this.line3 = value;
	}

	/**
	 * Gets the value of the locality property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getLocality() {
		return locality;
	}

	/**
	 * Sets the value of the locality property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setLocality(String value) {
		this.locality = value;
	}

	/**
	 * Gets the value of the city property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCity() {
		return city;
	}

	/**
	 * Sets the value of the city property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCity(String value) {
		this.city = value;
	}

	/**
	 * Gets the value of the state property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getState() {
		return state;
	}

	/**
	 * Sets the value of the state property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setState(String value) {
		this.state = value;
	}

	/**
	 * Gets the value of the country property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCountry() {
		return country;
	}

	/**
	 * Sets the value of the country property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCountry(String value) {
		this.country = value;
	}

	/**
	 * Gets the value of the zipCode property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getZipCode() {
		return zipCode;
	}

	/**
	 * Sets the value of the zipCode property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setZipCode(String value) {
		this.zipCode = value;
	}

	/**
	 * Gets the value of the contact1 property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getContact1() {
		return contact1;
	}

	/**
	 * Sets the value of the contact1 property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setContact1(String value) {
		this.contact1 = value;
	}

	/**
	 * Gets the value of the contact2 property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getContact2() {
		return contact2;
	}

	/**
	 * Sets the value of the contact2 property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setContact2(String value) {
		this.contact2 = value;
	}

	/**
	 * Gets the value of the addressType property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getAddressType() {
		return addressType;
	}

	/**
	 * Sets the value of the addressType property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setAddressType(String value) {
		this.addressType = value;
	}

	/**
	 * Gets the value of the company property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCompany() {
		return company;
	}

	/**
	 * Sets the value of the company property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCompany(String value) {
		this.company = value;
	}

	/**
	 * Gets the value of the latitude property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getLatitude() {
		return latitude;
	}

	/**
	 * Sets the value of the latitude property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setLatitude(String value) {
		this.latitude = value;
	}

	/**
	 * Gets the value of the longitude property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getLongitude() {
		return longitude;
	}

	/**
	 * Sets the value of the longitude property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setLongitude(String value) {
		this.longitude = value;
	}

	/**
	 * Gets the value of the preferredAddress property.
	 * 
	 * @return possible object is {@link Boolean }
	 * 
	 */
	public Boolean isPreferredAddress() {
		return preferredAddress;
	}

	/**
	 * Sets the value of the preferredAddress property.
	 * 
	 * @param value
	 *            allowed object is {@link Boolean }
	 * 
	 */
	public void setPreferredAddress(Boolean value) {
		this.preferredAddress = value;
	}

	@Override
	public String toString() {
		return line1 + ", " + line2 + ", " + locality + ", " + city + ", state:" + state + ", " + country + ", zipcode:"
				+ zipCode;
	}

	public String getObjectId() {
		return objectId;
	}

	public void setObjectId(String _id) {
		this.objectId = _id;
	}

	public Long getVersion() {
		return version;
	}

	public void setVersion(Long version) {
		this.version = version;
	}

	public String getDetachAll() {
		return detachAll;
	}

	public void setDetachAll(String detachAll) {
		this.detachAll = detachAll;
	}

	public Boolean getPreferredAddress() {
		return preferredAddress;
	}
	

}
