//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.19 at 03:23:59 PM IST 
//

package www.chaayos.com.chaimonkbluetoothapp.domain.model.new_model;


/**
 * <p>
 * Java class for IngredientType.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * <p>
 * 
 * <pre>
 * &lt;simpleType name="IngredientType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="NONE"/&gt;
 *     &lt;enumeration value="MENU_PRODUCT"/&gt;
 *     &lt;enumeration value="UNFINISHED_PRODUCT"/&gt;
 *     &lt;enumeration value="VARIENT"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
public enum IngredientType {

	NONE, MENU_PRODUCT, UNFINISHED_PRODUCT, VARIENT;

	public String value() {
		return name();
	}

	public static IngredientType fromValue(String v) {
		return valueOf(v);
	}

}
