/*
 * SUNSHINE TEAHOUSE PRIVATE LIMITED CONFIDENTIAL
 * __________________
 *
 * [2015] - [2017] Sunshine Teahouse Private Limited
 * All Rights Reserved.
 *
 * NOTICE:  All information contained herein is, and remains
 * the property of Sunshine Teahouse Private Limited and its suppliers,
 * if any.  The intellectual and technical concepts contained
 * herein are proprietary to Sunshine Teahouse Private Limited
 * and its suppliers, and are protected by trade secret or copyright law.
 * Dissemination of this information or reproduction of this material
 * is strictly forbidden unless prior written permission is obtained
 * from Sunshine Teahouse Private Limited.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.19 at 12:10:26 PM IST 
//

package www.chaayos.com.chaimonkbluetoothapp.domain.model.new_model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

public class ListData implements Serializable, Comparable<ListData> {

	private static final long serialVersionUID = 4514671108364575991L;

	protected IdCodeName detail;

	protected List<IdCodeName> content;

	public IdCodeName getDetail() {
		return detail;
	}

	public void setDetail(IdCodeName value) {
		this.detail = value;
	}

	public List<IdCodeName> getContent() {
		if (content == null) {
			content = new ArrayList<IdCodeName>();
		}
		return this.content;
	}

	@Override
	public int compareTo(ListData o) {
		return Integer.compare(this.getDetail().getId(), o.getDetail().getId());
	}

}
