/*
 * SUNSHINE TEAHOUSE PRIVATE LIMITED CONFIDENTIAL
 * __________________
 *
 * [2015] - [2017] Sunshine Teahouse Private Limited
 * All Rights Reserved.
 *
 * NOTICE:  All information contained herein is, and remains
 * the property of Sunshine Teahouse Private Limited and its suppliers,
 * if any.  The intellectual and technical concepts contained
 * herein are proprietary to Sunshine Teahouse Private Limited
 * and its suppliers, and are protected by trade secret or copyright law.
 * Dissemination of this information or reproduction of this material
 * is strictly forbidden unless prior written permission is obtained
 * from Sunshine Teahouse Private Limited.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.22 at 01:07:13 PM IST 
//

package www.chaayos.com.chaimonkbluetoothapp.domain.model.new_model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class Order implements Serializable{

	private static final long serialVersionUID = -7725662830415594342L;


	private String objectId;

	private Long version;

	private String detachAll;
	protected Integer orderId;
	protected String generateOrderId;
	protected Integer unitOrderId;
	protected Integer customerId;
	protected int employeeId;
	protected int pointsRedeemed;
	protected String source;
	protected String sourceId;
	protected boolean hasParcel;
	protected OrderStatus status;
	protected List<OrderItem> orders;
	protected List<EnquiryItem> enquiryItems;
	protected TransactionDetail transactionDetail;
	protected int printCount;
	protected SettlementType settlementType;
	protected List<Settlement> settlements;
	protected int unitId;
	protected String unitName;
	protected Integer terminalId;
	protected Date billStartTime;
	protected String billCreationTime;
	protected int channelPartner;
	protected int deliveryPartner;
	protected Subscription subscriptionDetail;
	protected String offerCode;
	protected List<ActionDetail> reprints;
	protected ActionDetail cancellationDetails;
	protected String orderRemark;
	protected Integer deliveryAddress;
	protected String customerName;
	protected List<OrderMetadata> metadataList;
	private BigDecimal totalAmount;

	
	public String getObjectId() {
		return objectId;
	}

	public void setObjectId(String objectId) {
		this.objectId = objectId;
	}

	public Integer getOrderId() {
		return orderId;
	}

	public void setOrderId(Integer value) {
		this.orderId = value;
	}

	public String getGenerateOrderId() {
		return generateOrderId;
	}

	public void setGenerateOrderId(String value) {
		this.generateOrderId = value;
	}

	public Integer getUnitOrderId() {
		return unitOrderId;
	}

	public void setUnitOrderId(Integer value) {
		this.unitOrderId = value;
	}

	public Integer getCustomerId() {
		return customerId;
	}


	public void setCustomerId(Integer value) {
		this.customerId = value;
	}

	/**
	 * Gets the value of the employeeId property.
	 * 
	 */
	public int getEmployeeId() {
		return employeeId;
	}

	/**
	 * Sets the value of the employeeId property.
	 * 
	 */
	public void setEmployeeId(int value) {
		this.employeeId = value;
	}

	/**
	 * Gets the value of the pointsRedeemed property.
	 * 
	 */
	public int getPointsRedeemed() {
		return pointsRedeemed;
	}

	/**
	 * Sets the value of the pointsRedeemed property.
	 * 
	 */
	public void setPointsRedeemed(int value) {
		this.pointsRedeemed = value;
	}

	/**
	 * Gets the value of the source property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSource() {
		return source;
	}

	/**
	 * Sets the value of the source property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSource(String value) {
		this.source = value;
	}

	/**
	 * Gets the value of the sourceId property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSourceId() {
		return sourceId;
	}

	/**
	 * Sets the value of the sourceId property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSourceId(String value) {
		this.sourceId = value;
	}

	/**
	 * Gets the value of the hasParcel property.
	 * 
	 */
	public boolean isHasParcel() {
		return hasParcel;
	}

	/**
	 * Sets the value of the hasParcel property.
	 * 
	 */
	public void setHasParcel(boolean value) {
		this.hasParcel = value;
	}

	/**
	 * Gets the value of the status property.
	 * 
	 * @return possible object is {@link OrderStatus }
	 * 
	 */
	public OrderStatus getStatus() {
		return status;
	}

	/**
	 * Sets the value of the status property.
	 * 
	 * @param value
	 *            allowed object is {@link OrderStatus }
	 * 
	 */
	public void setStatus(OrderStatus value) {
		this.status = value;
	}

	/**
	 * Gets the value of the orders property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the orders property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getOrders().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link OrderItem
	 * }
	 * 
	 * 
	 */
	public List<OrderItem> getOrders() {
		if (orders == null) {
			orders = new ArrayList<OrderItem>();
		}
		return this.orders;
	}

	/**
	 * Gets the value of the enquiryItems property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the enquiryItems property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getEnquiryItems().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link EnquiryItem }
	 * 
	 * 
	 */
	public List<EnquiryItem> getEnquiryItems() {
		if (enquiryItems == null) {
			enquiryItems = new ArrayList<EnquiryItem>();
		}
		return this.enquiryItems;
	}

	/**
	 * Gets the value of the transactionDetail property.
	 * 
	 * @return possible object is {@link TransactionDetail }
	 * 
	 */
	public TransactionDetail getTransactionDetail() {
		return transactionDetail;
	}

	/**
	 * Sets the value of the transactionDetail property.
	 * 
	 * @param value
	 *            allowed object is {@link TransactionDetail }
	 * 
	 */
	public void setTransactionDetail(TransactionDetail value) {
		this.transactionDetail = value;
	}

	/**
	 * Gets the value of the printCount property.
	 * 
	 */
	public int getPrintCount() {
		return printCount;
	}

	/**
	 * Sets the value of the printCount property.
	 * 
	 */
	public void setPrintCount(int value) {
		this.printCount = value;
	}

	/**
	 * Gets the value of the settlementType property.
	 * 
	 * @return possible object is {@link SettlementType }
	 * 
	 */
	public SettlementType getSettlementType() {
		return settlementType;
	}

	/**
	 * Sets the value of the settlementType property.
	 * 
	 * @param value
	 *            allowed object is {@link SettlementType }
	 * 
	 */
	public void setSettlementType(SettlementType value) {
		this.settlementType = value;
	}

	/**
	 * Gets the value of the settlements property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the settlements property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getSettlements().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link Settlement }
	 * 
	 * 
	 */
	public List<Settlement> getSettlements() {
		if (settlements == null) {
			settlements = new ArrayList<Settlement>();
		}
		return this.settlements;
	}

	/**
	 * Gets the value of the unitId property.
	 * 
	 */
	public int getUnitId() {
		return unitId;
	}

	/**
	 * Sets the value of the unitId property.
	 * 
	 */
	public void setUnitId(int value) {
		this.unitId = value;
	}

	/**
	 * Gets the value of the unitName property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getUnitName() {
		return unitName;
	}

	/**
	 * Sets the value of the unitName property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setUnitName(String value) {
		this.unitName = value;
	}

	/**
	 * Gets the value of the terminalId property.
	 * 
	 * @return possible object is {@link Integer }
	 * 
	 */
	public Integer getTerminalId() {
		return terminalId;
	}

	/**
	 * Sets the value of the terminalId property.
	 * 
	 * @param value
	 *            allowed object is {@link Integer }
	 * 
	 */
	public void setTerminalId(Integer value) {
		this.terminalId = value;
	}

	/**
	 * Gets the value of the billStartTime property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public Date getBillStartTime() {
		return billStartTime;
	}

	/**
	 * Sets the value of the billStartTime property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setBillStartTime(Date value) {
		this.billStartTime = value;
	}

	/**
	 * Gets the value of the billCreationTime property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getBillCreationTime() {
		return billCreationTime;
	}

	/**
	 * Sets the value of the billCreationTime property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setBillCreationTime(String value) {
		this.billCreationTime = value;
	}

	/**
	 * Gets the value of the billCreationSeconds property.
	 * 
	 */


	/**
	 * Gets the value of the billingServerTime property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */


	/**
	 * Gets the value of the channelPartner property.
	 * 
	 */
	public int getChannelPartner() {
		return channelPartner;
	}

	/**
	 * Sets the value of the channelPartner property.
	 * 
	 */
	public void setChannelPartner(int value) {
		this.channelPartner = value;
	}

	/**
	 * Gets the value of the deliveryPartner property.
	 * 
	 */
	public int getDeliveryPartner() {
		return deliveryPartner;
	}

	/**
	 * Sets the value of the deliveryPartner property.
	 * 
	 */
	public void setDeliveryPartner(int value) {
		this.deliveryPartner = value;
	}

	/**
	 * Gets the value of the subscriptionDetail property.
	 * 
	 * @return possible object is {@link Subscription }
	 * 
	 */
	public Subscription getSubscriptionDetail() {
		return subscriptionDetail;
	}

	/**
	 * Sets the value of the subscriptionDetail property.
	 * 
	 * @param value
	 *            allowed object is {@link Subscription }
	 * 
	 */
	public void setSubscriptionDetail(Subscription value) {
		this.subscriptionDetail = value;
	}

	/**
	 * Gets the value of the offerCode property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getOfferCode() {
		return offerCode;
	}

	/**
	 * Sets the value of the offerCode property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setOfferCode(String value) {
		this.offerCode = value;
	}

	/**
	 * Gets the value of the reprints property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the reprints property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getReprints().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link ActionDetail }
	 * 
	 * 
	 */
	public List<ActionDetail> getReprints() {
		if (reprints == null) {
			reprints = new ArrayList<ActionDetail>();
		}
		return this.reprints;
	}

	/**
	 * Gets the value of the cancellationDetails property.
	 * 
	 * @return possible object is {@link ActionDetail }
	 * 
	 */
	public ActionDetail getCancellationDetails() {
		return cancellationDetails;
	}

	/**
	 * Sets the value of the cancellationDetails property.
	 * 
	 * @param value
	 *            allowed object is {@link ActionDetail }
	 * 
	 */
	public void setCancellationDetails(ActionDetail value) {
		this.cancellationDetails = value;
	}

	/**
	 * Gets the value of the orderRemark property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getOrderRemark() {
		return orderRemark;
	}

	/**
	 * Sets the value of the orderRemark property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setOrderRemark(String value) {
		this.orderRemark = value;
	}

	/**
	 * Gets the value of the deliveryAddress property.
	 * 
	 * @return possible object is {@link Integer }
	 * 
	 */
	public Integer getDeliveryAddress() {
		return deliveryAddress;
	}

	/**
	 * Sets the value of the deliveryAddress property.
	 * 
	 * @param value
	 *            allowed object is {@link Integer }
	 * 
	 */
	public void setDeliveryAddress(Integer value) {
		this.deliveryAddress = value;
	}

	/**
	 * Gets the value of the customerName property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCustomerName() {
		return customerName;
	}

	/**
	 * Sets the value of the customerName property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCustomerName(String value) {
		this.customerName = value;
	}

	/**
	 * Gets the value of the metadataList property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the metadataList property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getMetadataList().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link OrderMetadata }
	 * 
	 * 
	 */
	public List<OrderMetadata> getMetadataList() {
		if (metadataList == null) {
			metadataList = new ArrayList<OrderMetadata>();
		}
		return this.metadataList;
	}

	public Long getVersion() {
		return version;
	}

	public void setVersion(Long version) {
		this.version = version;
	}

	public String getDetachAll() {
		return detachAll;
	}

	public void setDetachAll(String detachAll) {
		this.detachAll = detachAll;
	}

	public void setOrders(List<OrderItem> orders) {
		this.orders = orders;
	}

	public void setEnquiryItems(List<EnquiryItem> enquiryItems) {
		this.enquiryItems = enquiryItems;
	}

	public void setSettlements(List<Settlement> settlements) {
		this.settlements = settlements;
	}

	public void setReprints(List<ActionDetail> reprints) {
		this.reprints = reprints;
	}

	public void setMetadataList(List<OrderMetadata> metadataList) {
		this.metadataList = metadataList;
	}

	public BigDecimal getTotalAmount() {
		return totalAmount;
	}

	public void setTotalAmount(BigDecimal totalAmount) {
		this.totalAmount = totalAmount;
	}
}
