/*
 * SUNSHINE TEAHOUSE PRIVATE LIMITED CONFIDENTIAL
 * __________________
 *
 * [2015] - [2017] Sunshine Teahouse Private Limited
 * All Rights Reserved.
 *
 * NOTICE:  All information contained herein is, and remains
 * the property of Sunshine Teahouse Private Limited and its suppliers,
 * if any.  The intellectual and technical concepts contained
 * herein are proprietary to Sunshine Teahouse Private Limited
 * and its suppliers, and are protected by trade secret or copyright law.
 * Dissemination of this information or reproduction of this material
 * is strictly forbidden unless prior written permission is obtained
 * from Sunshine Teahouse Private Limited.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.19 at 12:10:26 PM IST 
//

package www.chaayos.com.chaimonkbluetoothapp.domain.model.new_model;


import java.io.Serializable;

public class ProductData implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -926969452764262475L;
	
	private String _id;
	private Long version;

	/**
	 * Added to avoid a runtime error whereby the detachAll property is checked
	 * for existence but not actually used.
	 */
	private String detachAll;
	protected int productId;
	protected String name;
	protected String code;
	protected String shortCode;
	protected String status;
	protected int type;
	protected int subType;
	protected boolean variantLevelOrdering;
	protected ProductClassification classification;
	protected boolean isInventoryTracked;

	
	public String get_id() {
		return _id;
	}

	public void set_id(String objectId) {
		this._id = objectId;
	}
	
	

	public Long getVersion() {
		return version;
	}

	public void setVersion(Long version) {
		this.version = version;
	}

	public String getDetachAll() {
		return detachAll;
	}

	public void setDetachAll(String detachAll) {
		this.detachAll = detachAll;
	}

	public int getProductId() {
		return productId;
	}

	public void setProductId(int id) {
		this.productId = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getShortCode() {
		return shortCode;
	}

	public void setShortCode(String shortCode) {
		this.shortCode = shortCode;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public boolean isInventoryTracked() {
		return isInventoryTracked;
	}

	public void setInventoryTracked(boolean isInventoryTracked) {
		this.isInventoryTracked = isInventoryTracked;
	}

	/**
	 * Gets the value of the type property.
	 * 
	 */
	public int getType() {
		return type;
	}

	/**
	 * Sets the value of the type property.
	 * 
	 */
	public void setType(int value) {
		this.type = value;
	}

	/**
	 * Gets the value of the subType property.
	 * 
	 */
	public int getSubType() {
		return subType;
	}

	/**
	 * Sets the value of the subType property.
	 * 
	 */
	public void setSubType(int value) {
		this.subType = value;
	}

	public boolean isVariantLevelOrdering() {
		return variantLevelOrdering;
	}

	public void setVariantLevelOrdering(boolean variantLevelOrdering) {
		this.variantLevelOrdering = variantLevelOrdering;
	}

	/**
	 * Gets the value of the isInventoryTracked property.
	 * 
	 */
	public boolean isIsInventoryTracked() {
		return isInventoryTracked;
	}

	/**
	 * Sets the value of the isInventoryTracked property.
	 * 
	 */
	public void setIsInventoryTracked(boolean value) {
		this.isInventoryTracked = value;
	}

	public ProductClassification getClassification() {
		return classification;
	}

	public void setClassification(ProductClassification classification) {
		this.classification = classification;
	}

	
}
