/*
 * SUNSHINE TEAHOUSE PRIVATE LIMITED CONFIDENTIAL
 * __________________
 *
 * [2015] - [2017] Sunshine Teahouse Private Limited
 * All Rights Reserved.
 *
 * NOTICE:  All information contained herein is, and remains
 * the property of Sunshine Teahouse Private Limited and its suppliers,
 * if any.  The intellectual and technical concepts contained
 * herein are proprietary to Sunshine Teahouse Private Limited
 * and its suppliers, and are protected by trade secret or copyright law.
 * Dissemination of this information or reproduction of this material
 * is strictly forbidden unless prior written permission is obtained
 * from Sunshine Teahouse Private Limited.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.18 at 03:33:20 PM IST 
//


package www.chaayos.com.chaimonkbluetoothapp.domain.model.new_model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;


/**
 * <p>Java class for Product complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Product"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="hasSizeProfile" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="hasAddons" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="subType" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="attribute" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="skuCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="billType" type="{http://www.w3schools.com}BillType"/&gt;
 *         &lt;element name="inventoryTracked" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="addOnProfile" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="dimensionProfileId" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="status" type="{http://www.w3schools.com}ProductStatus"/&gt;
 *         &lt;element name="startDate" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="endDate" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="supportsVariantLevelOrdering" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;sequence&gt;
 *           &lt;element name="prices" type="{http://www.w3schools.com}ProductPrice" maxOccurs="unbounded"/&gt;
 *         &lt;/sequence&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
public class Product  implements Serializable, Comparable<Product> {

	private static final long serialVersionUID = 6254972379595664500L;
	protected int id;
    protected String name;
    protected String description;
    protected boolean hasSizeProfile;
    protected boolean hasAddons;
    protected int type;
    protected int subType;
    protected String attribute;
    protected String skuCode;
    protected BillType billType;
	protected ProductClassification classification;
    protected String shortCode;
    protected boolean inventoryTracked;
    protected boolean employeeMealComponent;
    protected String addOnProfile;
    protected int dimensionProfileId;
    protected ProductStatus status;
    protected Date startDate;
    protected Date endDate;
    protected boolean supportsVariantLevelOrdering;
    protected List<ProductPrice> prices;

    /**
     * Gets the value of the id property.
     * 
     */
    public int getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(int value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the hasSizeProfile property.
     * 
     */
    public boolean isHasSizeProfile() {
        return hasSizeProfile;
    }

    /**
     * Sets the value of the hasSizeProfile property.
     * 
     */
    public void setHasSizeProfile(boolean value) {
        this.hasSizeProfile = value;
    }

    /**
     * Gets the value of the hasAddons property.
     * 
     */
    public boolean isHasAddons() {
        return hasAddons;
    }

    /**
     * Sets the value of the hasAddons property.
     * 
     */
    public void setHasAddons(boolean value) {
        this.hasAddons = value;
    }

    /**
     * Gets the value of the type property.
     * 
     */
    public int getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     */
    public void setType(int value) {
        this.type = value;
    }

    /**
     * Gets the value of the subType property.
     * 
     */
    public int getSubType() {
        return subType;
    }

    /**
     * Sets the value of the subType property.
     * 
     */
    public void setSubType(int value) {
        this.subType = value;
    }

    /**
     * Gets the value of the attribute property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttribute() {
        return attribute;
    }

    /**
     * Sets the value of the attribute property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttribute(String value) {
        this.attribute = value;
    }

    /**
     * Gets the value of the skuCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSkuCode() {
        return skuCode;
    }

    /**
     * Sets the value of the skuCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSkuCode(String value) {
        this.skuCode = value;
    }

    /**
     * Gets the value of the billType property.
     * 
     * @return
     *     possible object is
     *     {@link BillType }
     *     
     */
    public BillType getBillType() {
        return billType;
    }

    /**
     * Sets the value of the billType property.
     * 
     * @param value
     *     allowed object is
     *     {@link BillType }
     *     
     */
    public void setBillType(BillType value) {
        this.billType = value;
    }

    /**
     * Gets the value of the inventoryTracked property.
     * 
     */
    public boolean isInventoryTracked() {
        return inventoryTracked;
    }

    /**
     * Sets the value of the inventoryTracked property.
     * 
     */
    public void setInventoryTracked(boolean value) {
        this.inventoryTracked = value;
    }

    
    public boolean isEmployeeMealComponent() {
		return employeeMealComponent;
	}

	public void setEmployeeMealComponent(boolean employeeMealComponent) {
		this.employeeMealComponent = employeeMealComponent;
	}

	/**
     * Gets the value of the addOnProfile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddOnProfile() {
        return addOnProfile;
    }

    /**
     * Sets the value of the addOnProfile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddOnProfile(String value) {
        this.addOnProfile = value;
    }

    /**
     * Gets the value of the dimensionProfileId property.
     * 
     */
    public int getDimensionProfileId() {
        return dimensionProfileId;
    }

    /**
     * Sets the value of the dimensionProfileId property.
     * 
     */
    public void setDimensionProfileId(int value) {
        this.dimensionProfileId = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link ProductStatus }
     *     
     */
    public ProductStatus getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductStatus }
     *     
     */
    public void setStatus(ProductStatus value) {
        this.status = value;
    }

    /**
     * Gets the value of the startDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * Sets the value of the startDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStartDate(Date value) {
        this.startDate = value;
    }

    /**
     * Gets the value of the endDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * Sets the value of the endDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEndDate(Date value) {
        this.endDate = value;
    }

    /**
     * Gets the value of the supportsVariantLevelOrdering property.
     *
     */
    public boolean isSupportsVariantLevelOrdering() {
        return supportsVariantLevelOrdering;
    }

    /**
     * Sets the value of the supportsVariantLevelOrdering property.
     *
     */
    public void setSupportsVariantLevelOrdering(boolean value) {
        this.supportsVariantLevelOrdering = value;
    }

    /**
     * Gets the value of the prices property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the prices property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPrices().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProductPrice }
     * 
     * 
     */
    public List<ProductPrice> getPrices() {
        if (prices == null) {
            prices = new ArrayList<ProductPrice>();
        }
        return this.prices;
    }

	@Override
	public int compareTo(Product o) {
		return Integer.compare(this.getId(), o.getId());
	}

	public ProductClassification getClassification() {
		return classification;
	}

	public void setClassification(ProductClassification classification) {
		this.classification = classification;
	}

	public String getShortCode() {
		return shortCode;
	}

	public void setShortCode(String shortCode) {
		this.shortCode = shortCode;
	}
	
	
	
}
