//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.19 at 03:23:59 PM IST 
//

package www.chaayos.com.chaimonkbluetoothapp.domain.model.new_model;


import java.io.Serializable;
import java.util.Date;
import java.util.List;


public class RecipeDetail implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8770383427147819680L;
	private String _id;
	protected int recipeId;
	protected ProductData product;
	protected BasicInfo dimension;
	protected String name;
	protected String status = "ACTIVE";

	protected Date creationDate;

	protected Date modificationDate;

	protected Date startDate;

	protected Date endDate;
	protected boolean deliverable;
	protected IngredientDetail ingredient;
	protected List<IngredientProductDetail> addons;
	protected List<IngredientProductDetail> dineInConsumables;
	protected List<IngredientProductDetail> deliveryConsumables;
	protected List<IngredientProductDetail> takeawayConsumables;

	public String get_id() {
		return _id;
	}

	public void set_id(String objectId) {
		this._id = objectId;
	}

	/**
	 * Gets the value of the recipeId property.
	 * 
	 */
	public int getRecipeId() {
		return recipeId;
	}

	/**
	 * Sets the value of the recipeId property.
	 * 
	 */
	public void setRecipeId(int value) {
		this.recipeId = value;
	}

	/**
	 * Gets the value of the product property.
	 * 
	 * @return possible object is {@link ProductData }
	 * 
	 */
	public ProductData getProduct() {
		return product;
	}

	/**
	 * Sets the value of the product property.
	 * 
	 * @param value
	 *            allowed object is {@link ProductData }
	 * 
	 */
	public void setProduct(ProductData value) {
		this.product = value;
	}

	/**
	 * Gets the value of the dimension property.
	 * 
	 * @return possible object is {@link BasicInfo }
	 * 
	 */
	public BasicInfo getDimension() {
		return dimension;
	}

	/**
	 * Sets the value of the dimension property.
	 * 
	 * @param value
	 *            allowed object is {@link BasicInfo }
	 * 
	 */
	public void setDimension(BasicInfo value) {
		this.dimension = value;
	}

	/**
	 * Gets the value of the name property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getName() {
		return name;
	}

	/**
	 * Sets the value of the name property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setName(String value) {
		this.name = value;
	}

	/**
	 * Gets the value of the status property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * Sets the value of the status property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setStatus(String value) {
		this.status = value;
	}

	/**
	 * Gets the value of the creationDate property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public Date getCreationDate() {
		return creationDate;
	}

	/**
	 * Sets the value of the creationDate property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCreationDate(Date value) {
		this.creationDate = value;
	}

	/**
	 * Gets the value of the modificationDate property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public Date getModificationDate() {
		return modificationDate;
	}

	/**
	 * Sets the value of the modificationDate property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setModificationDate(Date value) {
		this.modificationDate = value;
	}

	/**
	 * Gets the value of the startDate property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public Date getStartDate() {
		return startDate;
	}

	/**
	 * Sets the value of the startDate property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setStartDate(Date value) {
		this.startDate = value;
	}

	/**
	 * Gets the value of the endDate property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public Date getEndDate() {
		return endDate;
	}

	/**
	 * Sets the value of the endDate property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setEndDate(Date value) {
		this.endDate = value;
	}

	/**
	 * Gets the value of the deliverable property.
	 * 
	 */
	public boolean isDeliverable() {
		return deliverable;
	}

	/**
	 * Sets the value of the deliverable property.
	 * 
	 */
	public void setDeliverable(boolean value) {
		this.deliverable = value;
	}

	/**
	 * Gets the value of the ingredient property.
	 * 
	 * @return possible object is {@link IngredientDetail }
	 * 
	 */
	public IngredientDetail getIngredient() {
		return ingredient;
	}

	/**
	 * Sets the value of the ingredient property.
	 * 
	 * @param value
	 *            allowed object is {@link IngredientDetail }
	 * 
	 */
	public void setIngredient(IngredientDetail value) {
		this.ingredient = value;
	}

	/**
	 * Gets the value of the addons property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the addons property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getAddons().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link IngredientProductDetail }
	 * 
	 * 
	 */
	public List<IngredientProductDetail> getAddons() {
		return this.addons;
	}

	/**
	 * Gets the value of the dineInConsumbales property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the dineInConsumbales property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getDineInConsumbales().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link IngredientProductDetail }
	 * 
	 * 
	 */
	public List<IngredientProductDetail> getDineInConsumables() {
		return this.dineInConsumables;
	}

	/**
	 * Gets the value of the deliveryConsumables property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the deliveryConsumables property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getDeliveryConsumables().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link IngredientProductDetail }
	 * 
	 * 
	 */
	public List<IngredientProductDetail> getDeliveryConsumables() {
		return this.deliveryConsumables;
	}

	/**
	 * Gets the value of the takeawayConsumables property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the takeawayConsumables property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getTakeawayConsumables().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link IngredientProductDetail }
	 * 
	 * 
	 */
	public List<IngredientProductDetail> getTakeawayConsumables() {
		return this.takeawayConsumables;
	}

	public void setAddons(List<IngredientProductDetail> addons) {
		this.addons = addons;
	}

	public void setDineInConsumables(List<IngredientProductDetail> dineInConsumables) {
		this.dineInConsumables = dineInConsumables;
	}

	public void setDeliveryConsumables(List<IngredientProductDetail> deliveryConsumables) {
		this.deliveryConsumables = deliveryConsumables;
	}

	public void setTakeawayConsumables(List<IngredientProductDetail> takeawayConsumables) {
		this.takeawayConsumables = takeawayConsumables;
	}

}
