/*
 * SUNSHINE TEAHOUSE PRIVATE LIMITED CONFIDENTIAL
 * __________________
 *
 * [2015] - [2017] Sunshine Teahouse Private Limited
 * All Rights Reserved.
 *
 * NOTICE:  All information contained herein is, and remains
 * the property of Sunshine Teahouse Private Limited and its suppliers,
 * if any.  The intellectual and technical concepts contained
 * herein are proprietary to Sunshine Teahouse Private Limited
 * and its suppliers, and are protected by trade secret or copyright law.
 * Dissemination of this information or reproduction of this material
 * is strictly forbidden unless prior written permission is obtained
 * from Sunshine Teahouse Private Limited.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.01 at 12:19:28 PM IST 
//

package www.chaayos.com.chaimonkbluetoothapp.domain.model.new_model;

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * <p>
 * Java class for TransactionDetail complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="TransactionDetail"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="saleAmount" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="totalAmount" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="taxableAmount" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="discountDetail" type="{http://www.w3schools.com}DiscountDetail"/&gt;
 *         &lt;element name="netPriceVat" type="{http://www.w3schools.com}PercentageDetail"/&gt;
 *         &lt;element name="mrpVat" type="{http://www.w3schools.com}PercentageDetail"/&gt;
 *         &lt;element name="surchargeOnTax" type="{http://www.w3schools.com}PercentageDetail"/&gt;
 *         &lt;element name="serviceTax" type="{http://www.w3schools.com}PercentageDetail"/&gt;
 *         &lt;element name="sbCess" type="{http://www.w3schools.com}PercentageDetail"/&gt;
 *         &lt;element name="kkCess" type="{http://www.w3schools.com}PercentageDetail"/&gt;
 *         &lt;element name="paidAmount" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="roundOffValue" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="savings" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
public class TransactionDetail implements Serializable{

	/**
	 * 
	 */
	private static final long serialVersionUID = -3256468249758673855L;

	private String objectId;

	private Long version;

	/**
	 * Added to avoid a runtime error whereby the detachAll property is checked
	 * for existence but not actually used.
	 */
	private String detachAll;
	protected BigDecimal saleAmount;
	protected BigDecimal totalAmount;
	protected BigDecimal taxableAmount;
	protected DiscountDetail discountDetail;
	protected PercentageDetail netPriceVat;
	protected PercentageDetail mrpVat;
	protected PercentageDetail surchargeOnTax;
	protected PercentageDetail serviceTax;
	protected PercentageDetail sbCess;
	protected PercentageDetail kkCess;
	protected BigDecimal paidAmount;
	protected BigDecimal roundOffValue;
	protected BigDecimal savings;

	public String getObjectId() {
		return objectId;
	}

	public void setObjectId(String _id) {
		this.objectId = _id;
	}

	public Long getVersion() {
		return version;
	}

	public void setVersion(Long version) {
		this.version = version;
	}

	public String getDetachAll() {
		return detachAll;
	}

	public void setDetachAll(String detachAll) {
		this.detachAll = detachAll;
	}

	/**
	 * Gets the value of the saleAmount property.
	 * 
	 * @return possible object is {@link BigDecimal }
	 * 
	 */
	public BigDecimal getSaleAmount() {
		return saleAmount;
	}

	/**
	 * Sets the value of the saleAmount property.
	 * 
	 * @param value
	 *            allowed object is {@link BigDecimal }
	 * 
	 */
	public void setSaleAmount(BigDecimal value) {
		this.saleAmount = value;
	}

	/**
	 * Gets the value of the totalAmount property.
	 * 
	 * @return possible object is {@link BigDecimal }
	 * 
	 */
	public BigDecimal getTotalAmount() {
		return totalAmount;
	}

	/**
	 * Sets the value of the totalAmount property.
	 * 
	 * @param value
	 *            allowed object is {@link BigDecimal }
	 * 
	 */
	public void setTotalAmount(BigDecimal value) {
		this.totalAmount = value;
	}

	/**
	 * Gets the value of the taxableAmount property.
	 * 
	 * @return possible object is {@link BigDecimal }
	 * 
	 */
	public BigDecimal getTaxableAmount() {
		return taxableAmount;
	}

	/**
	 * Sets the value of the taxableAmount property.
	 * 
	 * @param value
	 *            allowed object is {@link BigDecimal }
	 * 
	 */
	public void setTaxableAmount(BigDecimal value) {
		this.taxableAmount = value;
	}

	/**
	 * Gets the value of the discountDetail property.
	 * 
	 * @return possible object is {@link DiscountDetail }
	 * 
	 */
	public DiscountDetail getDiscountDetail() {
		return discountDetail;
	}

	/**
	 * Sets the value of the discountDetail property.
	 * 
	 * @param value
	 *            allowed object is {@link DiscountDetail }
	 * 
	 */
	public void setDiscountDetail(DiscountDetail value) {
		this.discountDetail = value;
	}

	/**
	 * Gets the value of the netPriceVat property.
	 * 
	 * @return possible object is {@link PercentageDetail }
	 * 
	 */
	public PercentageDetail getNetPriceVat() {
		return netPriceVat;
	}

	/**
	 * Sets the value of the netPriceVat property.
	 * 
	 * @param value
	 *            allowed object is {@link PercentageDetail }
	 * 
	 */
	public void setNetPriceVat(PercentageDetail value) {
		this.netPriceVat = value;
	}

	/**
	 * Gets the value of the mrpVat property.
	 * 
	 * @return possible object is {@link PercentageDetail }
	 * 
	 */
	public PercentageDetail getMrpVat() {
		return mrpVat;
	}

	/**
	 * Sets the value of the mrpVat property.
	 * 
	 * @param value
	 *            allowed object is {@link PercentageDetail }
	 * 
	 */
	public void setMrpVat(PercentageDetail value) {
		this.mrpVat = value;
	}

	/**
	 * Gets the value of the surchargeOnTax property.
	 * 
	 * @return possible object is {@link PercentageDetail }
	 * 
	 */
	public PercentageDetail getSurchargeOnTax() {
		return surchargeOnTax;
	}

	/**
	 * Sets the value of the surchargeOnTax property.
	 * 
	 * @param value
	 *            allowed object is {@link PercentageDetail }
	 * 
	 */
	public void setSurchargeOnTax(PercentageDetail value) {
		this.surchargeOnTax = value;
	}

	/**
	 * Gets the value of the serviceTax property.
	 * 
	 * @return possible object is {@link PercentageDetail }
	 * 
	 */
	public PercentageDetail getServiceTax() {
		return serviceTax;
	}

	/**
	 * Sets the value of the serviceTax property.
	 * 
	 * @param value
	 *            allowed object is {@link PercentageDetail }
	 * 
	 */
	public void setServiceTax(PercentageDetail value) {
		this.serviceTax = value;
	}

	/**
	 * Gets the value of the sbCess property.
	 * 
	 * @return possible object is {@link PercentageDetail }
	 * 
	 */
	public PercentageDetail getSbCess() {
		return sbCess;
	}

	/**
	 * Sets the value of the sbCess property.
	 * 
	 * @param value
	 *            allowed object is {@link PercentageDetail }
	 * 
	 */
	public void setSbCess(PercentageDetail value) {
		this.sbCess = value;
	}
	
	/**
	 * Gets the value of the kkCess property.
	 * 
	 * @return possible object is {@link PercentageDetail }
	 * 
	 */
	public PercentageDetail getKkCess() {
		return kkCess;
	}

	/**
	 * Sets the value of the kkCess property.
	 * 
	 * @param value
	 *            allowed object is {@link PercentageDetail }
	 * 
	 */
	public void setKkCess(PercentageDetail value) {
		this.kkCess = value;
	}

	/**
	 * Gets the value of the paidAmount property.
	 * 
	 * @return possible object is {@link BigDecimal }
	 * 
	 */
	public BigDecimal getPaidAmount() {
		return paidAmount;
	}

	/**
	 * Sets the value of the paidAmount property.
	 * 
	 * @param value
	 *            allowed object is {@link BigDecimal }
	 * 
	 */
	public void setPaidAmount(BigDecimal value) {
		this.paidAmount = value;
	}

	/**
	 * Gets the value of the roundOffValue property.
	 * 
	 * @return possible object is {@link BigDecimal }
	 * 
	 */
	public BigDecimal getRoundOffValue() {
		return roundOffValue;
	}

	/**
	 * Sets the value of the roundOffValue property.
	 * 
	 * @param value
	 *            allowed object is {@link BigDecimal }
	 * 
	 */
	public void setRoundOffValue(BigDecimal value) {
		this.roundOffValue = value;
	}

	/**
	 * Gets the value of the savings property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public BigDecimal getSavings() {
		return savings;
	}

	/**
	 * Sets the value of the savings property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSavings(BigDecimal value) {
		this.savings = value;
	}

}
