/*
 * SUNSHINE TEAHOUSE PRIVATE LIMITED CONFIDENTIAL
 * __________________
 *
 * [2015] - [2017] Sunshine Teahouse Private Limited
 * All Rights Reserved.
 *
 * NOTICE:  All information contained herein is, and remains
 * the property of Sunshine Teahouse Private Limited and its suppliers,
 * if any.  The intellectual and technical concepts contained
 * herein are proprietary to Sunshine Teahouse Private Limited
 * and its suppliers, and are protected by trade secret or copyright law.
 * Dissemination of this information or reproduction of this material
 * is strictly forbidden unless prior written permission is obtained
 * from Sunshine Teahouse Private Limited.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.04 at 12:52:40 PM IST 
//


package www.chaayos.com.chaimonkbluetoothapp.domain.model.new_model;

/**
 * <p>Java class for UnitSubCategory.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="UnitSubCategory"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="BPC"/&gt;
 *     &lt;enumeration value="COD"/&gt;
 *     &lt;enumeration value="HSC"/&gt;
 *     &lt;enumeration value="MALL"/&gt;
 *     &lt;enumeration value="TG"/&gt;
 *     &lt;enumeration value="INTL"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
public enum UnitSubCategory {

    BPC,
    COD,
    HSC,
    MALL,
    TG,
    INTL;

    public String value() {
        return name();
    }

    public static UnitSubCategory fromValue(String v) {
        return valueOf(v);
    }

}
