/*
 * SUNSHINE TEAHOUSE PRIVATE LIMITED CONFIDENTIAL
 * __________________
 *
 * [2015] - [2017] Sunshine Teahouse Private Limited
 * All Rights Reserved.
 *
 * NOTICE:  All information contained herein is, and remains
 * the property of Sunshine Teahouse Private Limited and its suppliers,
 * if any.  The intellectual and technical concepts contained
 * herein are proprietary to Sunshine Teahouse Private Limited
 * and its suppliers, and are protected by trade secret or copyright law.
 * Dissemination of this information or reproduction of this material
 * is strictly forbidden unless prior written permission is obtained
 * from Sunshine Teahouse Private Limited.
 */

package www.chaayos.com.chaimonkbluetoothapp.data.model;
// Generated 27 Jul, 2015 12:04:59 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * OrderSettlement generated by hbm2java
 */
public class OrderRePrintDetail implements java.io.Serializable {

	private Integer orderPrintId;
	private int orderDetailId;
	private String printReason;
	private int generatedBy;
	private Date reprintTime;

	public OrderRePrintDetail() {}

	public OrderRePrintDetail(int orderDetail, String printReason) {
		this.orderDetailId = orderDetail;
		this.printReason = printReason;
	}

	public OrderRePrintDetail(int orderDetail, String printReason, int generatedBy, int approvedBy,
			Date reprintTime) {
		this.orderDetailId = orderDetail;
		this.printReason = printReason;
		this.generatedBy = generatedBy;
		this.reprintTime = reprintTime;
	}


	public Integer getOrderPrintId() {
		return this.orderPrintId;
	}

	public void setOrderPrintId(Integer orderPrintId) {
		this.orderPrintId = orderPrintId;
	}

	public String getPrintReason() {
		return printReason;
	}

	public void setPrintReason(String printReason) {
		this.printReason = printReason;
	}


	public int getGeneratedBy() {
		return generatedBy;
	}

	public void setGeneratedBy(int employeeId) {
		this.generatedBy = employeeId;
	}

	public Date getReprintTime() {
		return reprintTime;
	}

	public void setReprintTime(Date billStartTime) {
		this.reprintTime = billStartTime;
	}


	public int getOrderDetailId() {
		return orderDetailId;
	}

	public void setOrderDetailId(int orderDetailId) {
		this.orderDetailId = orderDetailId;
	}
}
