/*
 * SUNSHINE TEAHOUSE PRIVATE LIMITED CONFIDENTIAL
 * __________________
 *
 * [2015] - [2017] Sunshine Teahouse Private Limited
 * All Rights Reserved.
 *
 * NOTICE:  All information contained herein is, and remains
 * the property of Sunshine Teahouse Private Limited and its suppliers,
 * if any.  The intellectual and technical concepts contained
 * herein are proprietary to Sunshine Teahouse Private Limited
 * and its suppliers, and are protected by trade secret or copyright law.
 * Dissemination of this information or reproduction of this material
 * is strictly forbidden unless prior written permission is obtained
 * from Sunshine Teahouse Private Limited.
 */

package www.chaayos.com.chaimonkbluetoothapp.data.model;

// Generated 27 Jul, 2015 12:04:59 PM by Hibernate Tools 4.0.0

import java.util.ArrayList;
import java.util.List;

import www.chaayos.com.chaimonkbluetoothapp.domain.model.new_model.OrderStatus;

/**
 * OrderInfo generated by hbm2java
 */
public class OrderDetail implements java.io.Serializable {

	private static final long serialVersionUID = 5441681397850434848L;

	private Integer orderId;
	private int generatedOrderId;
    private int token;
	private Integer customerId;
	private String customerName;
	private int empId;
	private OrderStatus orderStatus;
	private String settlementType;
	private int unitId;
	private String businessDate;
	private String billGenerationTime;
	private String billCancellationTime;
	private String billSettlementTime;
	private String billCompletionTime;
	private double totalAmount;
	private double netPriceVatPercent;
	private double netPriceVatAmount;
	private double mrpVatPercent;
	private double mrpVatAmount;
	private double serviceTaxPercent;
	private double serviceTaxAmount;
	private double sbCessPercent;
	private double sbCessAmount;
	private double kkCessPercent;
	private double kkCessAmount;
	private double surchargeTaxPercent;
	private double surchargeTaxAmount;
	private double roundOffAmount;
	private double settledAmount;
	private List<OrderItem> orderItems = new ArrayList<OrderItem>(0);
	private List<OrderSettlement> orderSettlements = new ArrayList<OrderSettlement>(0);
	private List<OrderRePrintDetail> orderReprints = new ArrayList<OrderRePrintDetail>(0);
	

    public OrderDetail(){

    }
	public OrderDetail(Integer orderId, int generatedOrderId,int token, int empId, int unitId,
					   OrderStatus orderStatus,String billGenerationTime, double totalAmount,
					   List<OrderItem> orderItems) {
		this.orderId = orderId;
		this.generatedOrderId = generatedOrderId;
        this.token = token;
		this.empId = empId;
		this.orderStatus = orderStatus;
		this.unitId = unitId;
		this.billGenerationTime = billGenerationTime;
		this.totalAmount = totalAmount;
		this.orderItems = orderItems;
	}


	public Integer getOrderId() {
		return this.orderId;
	}

	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}


	public int getGeneratedOrderId() {
		return this.generatedOrderId;
	}

	public void setGeneratedOrderId(int generatedOrderId) {
		this.generatedOrderId = generatedOrderId;
	}

	public Integer getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(Integer customerId) {
		this.customerId = customerId;
	}

	public int getEmpId() {
		return this.empId;
	}

	public void setEmpId(int empId) {
		this.empId = empId;
	}

	public String getSettlementType() {
		return this.settlementType;
	}

	public void setSettlementType(String settlementType) {
		this.settlementType = settlementType;
	}

	public int getUnitId() {
		return this.unitId;
	}

	public void setUnitId(int unitId) {
		this.unitId = unitId;
	}


	public double getTotalAmount() {
		return this.totalAmount;
	}

	public void setTotalAmount(double totalAmount) {
		this.totalAmount = totalAmount;
	}

	public double getNetPriceVatPercent() {
		return this.netPriceVatPercent;
	}

	public void setNetPriceVatPercent(double netPriceVatPercent) {
		this.netPriceVatPercent = netPriceVatPercent;
	}

	public double getNetPriceVatAmount() {
		return this.netPriceVatAmount;
	}

	public void setNetPriceVatAmount(double netPriceVatAmount) {
		this.netPriceVatAmount = netPriceVatAmount;
	}

	public double getMrpVatPercent() {
		return this.mrpVatPercent;
	}

	public void setMrpVatPercent(double mrpVatPercent) {
		this.mrpVatPercent = mrpVatPercent;
	}

	public double getMrpVatAmount() {
		return this.mrpVatAmount;
	}

	public void setMrpVatAmount(double mrpVatAmount) {
		this.mrpVatAmount = mrpVatAmount;
	}

	public double getServiceTaxPercent() {
		return this.serviceTaxPercent;
	}

	public void setServiceTaxPercent(double serviceTaxPercent) {
		this.serviceTaxPercent = serviceTaxPercent;
	}

	public double getServiceTaxAmount() {
		return this.serviceTaxAmount;
	}

	public void setServiceTaxAmount(double serviceTaxAmount) {
		this.serviceTaxAmount = serviceTaxAmount;
	}
	public double getSbCessPercent() {
		return this.sbCessPercent;
	}

	public void setSbCessPercent(double sbCessPercent) {
		this.sbCessPercent = sbCessPercent;
	}

	public double getKkCessAmount() {
		return this.kkCessAmount;
	}

	public void setKkCessAmount(double kkCessAmount) {
		this.kkCessAmount = kkCessAmount;
	}

	public double getKkCessPercent() {
		return this.kkCessPercent;
	}

	public void setKkCessPercent(double kkCessPercent) {
		this.kkCessPercent = kkCessPercent;
	}

	public double getSbCessAmount() {
		return this.sbCessAmount;
	}

	public void setSbCessAmount(double sbCessAmount) {
		this.sbCessAmount = sbCessAmount;
	}
	
	public double getSurchargeTaxPercent() {
		return this.surchargeTaxPercent;
	}
	
	

	public void setSurchargeTaxPercent(double surchargeTaxPercent) {
		this.surchargeTaxPercent = surchargeTaxPercent;
	}

	public double getSurchargeTaxAmount() {
		return this.surchargeTaxAmount;
	}

	public void setSurchargeTaxAmount(double surchargeTaxAmount) {
		this.surchargeTaxAmount = surchargeTaxAmount;
	}

	public double getRoundOffAmount() {
		return this.roundOffAmount;
	}

	public void setRoundOffAmount(double roundOffAmount) {
		this.roundOffAmount = roundOffAmount;
	}

	public double getSettledAmount() {
		return this.settledAmount;
	}

	public void setSettledAmount(double settledAmount) {
		this.settledAmount = settledAmount;
	}

	public List<OrderItem> getOrderItems() {
		return this.orderItems;
	}

	public void setOrderItems(List<OrderItem> orderItems) {
		this.orderItems = orderItems;
	}

	public List<OrderSettlement> getOrderSettlements() {
		return this.orderSettlements;
	}

	public void setOrderSettlements(List<OrderSettlement> orderSettlements) {
		this.orderSettlements = orderSettlements;
	}

	public List<OrderRePrintDetail> getOrderReprints() {
		return orderReprints;
	}

	public void setOrderReprints(List<OrderRePrintDetail> orderReprints) {
		this.orderReprints = orderReprints;
	}

    public String getCustomerName() {
        return customerName;
    }

    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }

	public OrderStatus getOrderStatus() {
		return orderStatus;
	}

	public void setOrderStatus(OrderStatus orderStatus) {
		this.orderStatus = orderStatus;
	}

    public int getToken() {
        return token;
    }

    public void setToken(int token) {
        this.token = token;
    }

    public String getBillGenerationTime() {
        return billGenerationTime;
    }

    public void setBillGenerationTime(String billGenerationTime) {
        this.billGenerationTime = billGenerationTime;
    }

    public String getBillCancellationTime() {
        return billCancellationTime;
    }

    public void setBillCancellationTime(String billCancellationTime) {
        this.billCancellationTime = billCancellationTime;
    }

    public String getBillSettlementTime() {
        return billSettlementTime;
    }

    public void setBillSettlementTime(String billSettlementTime) {
        this.billSettlementTime = billSettlementTime;
    }

    public String getBillCompletionTime() {
        return billCompletionTime;
    }

    public void setBillCompletionTime(String billCompletionTime) {
        this.billCompletionTime = billCompletionTime;
    }

	public String getBusinessDate() {
		return businessDate;
	}

	public void setBusinessDate(String businessDate) {
		this.businessDate = businessDate;
	}
}
