/*
 * SUNSHINE TEAHOUSE PRIVATE LIMITED CONFIDENTIAL
 * __________________
 *
 * [2015] - [2017] Sunshine Teahouse Private Limited
 * All Rights Reserved.
 *
 * NOTICE:  All information contained herein is, and remains
 * the property of Sunshine Teahouse Private Limited and its suppliers,
 * if any.  The intellectual and technical concepts contained
 * herein are proprietary to Sunshine Teahouse Private Limited
 * and its suppliers, and are protected by trade secret or copyright law.
 * Dissemination of this information or reproduction of this material
 * is strictly forbidden unless prior written permission is obtained
 * from Sunshine Teahouse Private Limited.
 */

package www.chaayos.com.chaimonkbluetoothapp.data.model;
// Generated 27 Jul, 2015 12:04:59 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;

/**
 * OrderSettlement generated by hbm2java
 */

public class OrderSettlement implements java.io.Serializable {

	private Integer settlementId;
	private int  orderDetailId;
	private int paymentModeId;
	private BigDecimal amountPaid;
	private BigDecimal roundOffAmount;

	public OrderSettlement() {
	}

	public OrderSettlement(int orderDetailId, int paymentModeId) {
		this.orderDetailId = orderDetailId;
		this.paymentModeId = paymentModeId;
	}

	public OrderSettlement(int orderDetailId, int paymentModeId, BigDecimal amountPaid,
			BigDecimal roundOffAmount) {
		this.orderDetailId = orderDetailId;
		this.paymentModeId = paymentModeId;
		this.amountPaid = amountPaid;
		this.roundOffAmount = roundOffAmount;
	}

	public Integer getSettlementId() {
		return this.settlementId;
	}

	public void setSettlementId(Integer settlementId) {
		this.settlementId = settlementId;
	}

	public int getPaymentModeId() {
		return this.paymentModeId;
	}

	public void setPaymentModeId(int paymentModeId) {
		this.paymentModeId = paymentModeId;
	}

	public BigDecimal getAmountPaid() {
		return this.amountPaid;
	}

	public void setAmountPaid(BigDecimal amountPaid) {
		this.amountPaid = amountPaid;
	}

	public BigDecimal getRoundOffAmount() {
		return this.roundOffAmount;
	}

	public void setRoundOffAmount(BigDecimal roundOffAmount) {
		this.roundOffAmount = roundOffAmount;
	}

	public int getOrderDetailId() {
		return orderDetailId;
	}

	public void setOrderDetailId(int orderDetailId) {
		this.orderDetailId = orderDetailId;
	}
}
